profile: dev

kafka:
  bootstrapserver: "localhost:9094"
  groupid: GitOperatorCG
  sessiontimeout: 5000
  eventschannelenabled: true  
  rebalanceenabled: true
  partitioneofenabled: true
  autooffset: earliest
  consumertopic: gitoperator-in
  gitactionbacktopic: gitoperator-out
  messageminsize: 10e3
  messagemaxsize: 10e6

gitserver:
  url: http://localhost:3000
  authtoken: 1234sw
  username: TestOrchestrator
  password: TestOrchestrator
  email: TestOrchestrator@xqledger.com
  localreposlocation: "/var/git/repos/"
  repository: TestRepo

  


