profile: default

kafka:
  bootstrapserver: "kafka:9094"
  groupid: GitOperatorCG
  sessiontimeout: 5000
  eventschannelenabled: true  
  rebalanceenabled: true
  partitioneofenabled: true
  autooffset: earliest
  consumertopic: gitoperator-in
  consumertopicbatch: gitoperator-batch-in
  gitactionbacktopic: gitoperator-out
  messageminsize: 10e3
  messagemaxsize: 10e6

gitserver:
  url: "http://git-server:3000"
  authtoken: ""
  username: TestOrchestrator
  password: TestOrchestrator
  email: TestOrchestratorApp@xqledger.com
  localreposlocation: "/var/git/repositories/"

