profile: dev

kafka:
  bootstrapserver: 127.0.0.1:9094
  groupid: GitOperatorCG
  sessiontimeout: 5000
  eventschannelenabled: true  
  rebalanceenabled: true
  partitioneofenabled: true
  autooffset: earliest
  consumertopic: gitoperator-in
  gitactionbacktopic: gitoperator-out
  messageminsize: 10e3
  messagemaxsize: 10e6

gitserver:
  url: http://localhost:3000
  authtoken: ""
  username: TestOrchestrator
  password: TestOrchestrator
  email: testorchestrator@gmail.com
  localreposlocation: "/var/git/repos"

  


