profile: dev

kafka:
  bootstrapserver: 127.0.0.1:9094
  groupid: GitOperatorCG
  sessiontimeout: 5000
  eventschannelenabled: true  
  rebalanceenabled: true
  partitioneofenabled: true
  autooffset: earliest
  consumertopic: gitoperator-in
  consumertopicbatch: gitoperator-batch-in
  gitactionbacktopic: gitoperator-out
  messageminsize: 10e3
  messagemaxsize: 10e6

gitserver:
  url: http://localhost:3000/api/v1
  authtoken: "token 673af4a51987715e1ec5a41cd8e1742437b5ba19"
  username: TestOrchestrator
  password: TestOrchestrator
  email: testorchestrator@xqledger.com
  localreposlocation: "/var/git/repos"
  timeout: 10000
  


