profile: integration

kafka:
  bootstrapserver: "localhost:9094"
  groupid: GitOperatorCG
  sessiontimeout: 5000
  eventschannelenabled: true  
  rebalanceenabled: true
  partitioneofenabled: true
  autooffset: earliest
  consumertopic: gitoperator-in
  gitactionbacktopic: gitoperator-out
  alerttopic: outgoing_alert
  messageminsize: 10e3
  messagemaxsize: 10e6

units:
  - name: UsFirst
    alias: test
    repo: GoNoSQL_1
  - name: UKBusiness
    alias: english
    repo: GoNoSQL_2

gitserver:
  localbasicpath: "/home/administrator/go/src/me/gitpoc/"
  url: "localhost:3000"
  authtoken: ""
  username: jdediego
  password: "Turing_326"
  email: "jesus.dediego.erles@gmail.com"



    
  


